# Use postgres/example user/password credentials

services:

  db:
    image: postgres
    restart: always
    shm_size: 4g
    environment:
      POSTGRES_PASSWORD: password_mocaccino
      POSTGRES_USER: mocaccino
      POSTGRES_DB: mocaccino_db
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
