services:
  postgres:
    image: postgres:15
    container_name: moccacino_postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: moccacino_user
      POSTGRES_PASSWORD: moccacino_password
      POSTGRES_DB: moccacino_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: